- hosts: vms
  vars:
    users:
      - { name: root, path: './files/ssh_keys/root/id_rsa.pub' }

  tasks:
    - name: Первый вход по SSH
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', item.path) }}"
        manage_dir: false
      loop: "{{ users }}"
      become: true

    - name: Загрузка SSH ключей пользователям
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', item.path) }}"
        manage_dir: false
      loop: "{{ users }}"
      become: true