- hosts: vm_1, vm_2
  vars:
    nginx_port: 108
    root_dir: /usr/share/nginx/html

  tasks:
    - name:
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: true

    - name: copy index.html
      ansible.builtin.template:
        src: ./index.html
        dest: "{{ root_dir }}/index.html"
        owner: makso
        group: makso
        mode: '0744'
      become: true

    - name: copy nginx.conf
      ansible.builtin.template:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: makso
        group: makso
        mode: '0744'
      notify:
        - restart nginx
      become: true

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true