- hosts: vm_1, vm_2

  tasks:
    - name:
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
      become: true

    - name:
      ansible.builtin.apt:
        name: cowsay
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
      become: true

    - name: Запуск утилиты "Корова гворит"
      ansible.builtin.command: cowsay Это сервер {{ board_name | upper }}
      register: cowsay_result

    - name: copy index.html
      ansible.builtin.template:
        src: ./files/html/index.html
        dest: "{{ root_dir }}/index.html"
        owner: makso
        group: makso
        mode: '0744'
      become: true

    - name: copy nginx.conf
      ansible.builtin.template:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: makso
        group: makso
        mode: '0744'
      notify:
        - restart nginx
      become: true

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true